### ISSUE TITLE
Merge with `devie-bot`

### ISSUE THREAD

**Issue by with-heart** [Developer-DAO/devie-bot#17]
Hi yall! 👋 

I wanted to open this issue as sort of a mirror of https://github.com/Developer-DAO/devie-bot/issues/1. I agree with @fiigmnt's proposal that we should merge `devie-bot` and `discord-resource-bot`.

I'd like to extend from his proposal by proposing that we take the following actions:

- Since `discord-resource-bot` has an ecosystem already (events, commands, tooling, TypeScript support, beginnings of a test framework, etc.) while `devie-bot` is currently a single event, open a PR to `discord-resource-bot` adding the `devie-bot` event
- Merge permissions for both bots into Resource Bot
- Delete the `devie-bot` branch & rename this repo to `devie-bot`
- Rebrand Resource Bot to Devie

I think these changes would be less effort than merging all of `discord-resource-bot` into `devie-bot` while retaining the more general-purpose and friendly branding of Devie.

What do yall think? 

If we'd like to go this route, I'll break the tasks above into sub-tasks so we can tackle them one-by-one.

**Comment by AidenMontgomery** [comment]
I have linked the PR that contains the changes required to bring `devie-bot` functionality into this repo.
Specifically this commit - 8378e26133ad72d6f61c09a2be05fcf8b3f41b46

I have also experimented with `git replace --graft` to essentially `rebase` this repo on `devie-bot` to maintain the history of both repos and hopefully allow us to push the merged bot straight into `devie-bot`'s repo.

I have no preference to where we continue to develop the bot once the linked PR is merged.

The PR includes setting the `Intents` and `Partials` required for `devie-bot`'s functionality.

As for permissions, I have found that someone who can access the discord server's settings can actually update the permissions on an existing bot, rather than kicking and re-inviting.

```
server settings -> roles -> <bot name> -> edit -> permissions
```

However, I understand that it might be difficult to update the avatar of existing bots, https://www.reddit.com/r/discordapp/comments/a0d7jf/discord_appbot_avatar_not_updating/

The PR has progressed somewhat since the last time it was reviewed, so would be good to get some more feedback on it and then get it merged.

(Originally linked the wrong PR, sorry!)
